Update 5g-on-helium.mdx
helium/docs pull request #1159
Opened 2023-03-20 00:38 UTC by waveform06

Updated with new Emissions information and Solana dates.

2023-03-20 17:59 UTC, jthiller commented on docs/5g-on-helium/5g-on-helium.mdx
> +[HIP-75](https://github.com/helium/HIP/blob/main/0075-mobile-poc-initiate-programmatic-minting-and-updated-emissions-curve.md#economic-changes-to-emissions-curve) further modifiled the emission sched
Would be good to just lay out the emissions schedule rather than pointing to HIPs

2023-03-20 17:59 UTC, jthiller commented on docs/5g-on-helium/5g-on-helium.mdx
> +aligned withthe HNT issuance halvenings. The first halving will occur on August 1, 2023, to align
```suggestion
aligned with the HNT issuance halvenings. The first MOBILE halving will occur on August 1, 2023, to align 
```

2023-03-20 18:00 UTC, jthiller commented on docs/5g-on-helium/5g-on-helium.mdx
> +The date for the treasury implementation is April 18th 2023 and dependent on core developers
```suggestion
The date for the treasury implementation is April 18, 2023 and dependent on core developers 
```

2023-03-20 18:14 UTC, jthiller requested changes
couple of typos in here

2023-03-21 20:31 UTC, samgutentag commented on docs/5g-on-helium/5g-on-helium.mdx
> +[HIP-75](https://github.com/helium/HIP/blob/main/0075-mobile-poc-initiate-programmatic-minting-and-updated-emissions-curve.md#economic-changes-to-emissions-curve) further modifiled the emission sched
added emissions table in change [0ca2a35](https://github.com/helium/docs/pull/1159/commits/0ca2a358e345cd585a2e088860c67edfefd01900)

2023-03-21 23:29 UTC, jthiller approved these changes

2023-03-21 23:29 UTC, merged