removing unused image files
helium/docs pull request #1173
Opened 2023-03-24 07:32 UTC by samgutentag

these image files are not used in any docs pages and can be safely removed

2023-03-24 21:21 UTC, jthiller requested changes
We'll want to use a couple of these.

2023-03-24 21:21 UTC, jthiller commented on static/img/5g-on-helium/mobile-header.png
We might want this one for the MOBILE page.

2023-03-24 21:21 UTC, jthiller commented on static/img/home/docsheader.png
Will want this one when we complete the migration and revert the home page.

2023-03-24 21:21 UTC, jthiller commented on static/img/validators/faucet.png
Might be worth keeping around.

2023-03-27 18:20 UTC, samgutentag commented on static/img/5g-on-helium/mobile-header.png
restored!

2023-03-27 18:20 UTC, samgutentag commented on static/img/validators/faucet.png
restored!

2023-03-27 18:20 UTC, samgutentag commented on static/img/home/docsheader.png
restored!

2023-03-28 00:45 UTC, jthiller approved these changes
Thx!

2023-03-30 21:04 UTC, merged