Update maker-apps.mdx
helium/docs pull request #1233
Opened 2023-04-19 12:06 UTC by waveform06

several minor updates

2023-04-20 03:35 UTC, jthiller requested changes, later dismissed

2023-04-20 03:35 UTC, jthiller commented on docs/hotspot-makers/maker-apps.mdx
> +to onboard their Hotspots, assert Hotspot locations and maintain their Hotspots with diagnostic tools,
Should be a comma after 'Hotspot locations' (Oxford comma).
One too many 'and's in this sentence:
"assert Hotspot locations **and** maintain"
"diagnostic tools, **and** various basic troubleshooting tools."

2023-04-20 03:35 UTC, jthiller commented on docs/hotspot-makers/maker-apps.mdx
> +FreedomFI hotspots can now use the Helium Hotspot App to onboard and manage
```suggestion
FreedomFI Hotspots can now use the Helium Hotspot App to onboard and manage
```

2023-04-21 22:30 UTC, samgutentag approved these changes

2023-04-21 22:30 UTC, merged