Solana FAQ Editorial added to Sidebar
helium/docs pull request #1291
Opened 2023-04-25 22:40 UTC by samgutentag

2023-04-26 15:12 UTC, jthiller requested changes
Do we need a netlify redirect for the changed /faq/solana-migration file?

2023-04-26 15:12 UTC, jthiller commented on docs/solana/migration-faq.mdx
> +## Why Does My Helium Wallet App Crash When I Open It?
Let's move this one way down the list. A bit nicer to kick off with the SOL question. Odds are this is quickly solved as long as people are getting automatic updates.

2023-04-26 21:30 UTC, samgutentag commented on docs/solana/migration-faq.mdx
> +## Why Does My Helium Wallet App Crash When I Open It?
fixed!

2023-04-26 21:30 UTC, samgutentag commented
> Do we need a netlify redirect for the changed /faq/solana-migration file?

the old page name was never actually linked on the sidebar, no need for a redirect

2023-04-27 00:38 UTC, jthiller approved these changes

2023-04-27 01:44 UTC, merged