Wallet user update
helium/docs pull request #1720
Opened 2024-01-15 10:41 UTC by waveform06

Post solana phrasing with updates and added info on how to identify migrated wallet.

2024-01-15 10:56 UTC, waveform06 commented
Actually helium hotspot app needs to be 2.0.8 or higher

2024-01-16 18:18 UTC, jthiller requested changes

2024-01-16 18:18 UTC, jthiller commented on docs/architecture/solana/migration/wallet-user.mdx
> +clicking the "Seed Wallet" buttton. Wallets seeded/migrated will have 0.00139088 SOL deposited in
typo, "buttton"

2024-01-16 18:18 UTC, jthiller commented on docs/architecture/solana/migration/wallet-user.mdx
> +Hotspots are now managed with Maker Apps or the Helium Wallet.
Should downplay maker apps as we're working to bring these features back to Helium Wallet.

2024-01-16 18:18 UTC, jthiller commented on docs/architecture/solana/migration/wallet-user.mdx
> +the Helium Wallet app version **2.0.0** or later. The latest versions of each app are recommended.
"The latest versions of each app are recommended." not needed

2024-02-19 23:10 UTC, jthiller approved these changes

2024-02-19 23:22 UTC, merged