Updated some of 'IoT Network' subsections
helium/docs pull request #1765
Opened 2024-02-04 19:47 UTC by Dumpling-girl

Updated The Helium IOT Network section.
Updated Helium LoRaWAN section.

#Solana Scribes 2024

2024-02-08 00:05 UTC, jthiller requested changes

2024-02-08 00:05 UTC, jthiller commented on docs/network-iot/iot.mdx
> +        <img className="docicon" src={useBaseUrl('img/icons/docicon.svg')} /> Earn IOT
Let's keep this change in #1751

2024-02-08 00:05 UTC, jthiller commented on docs/network-iot/lorawan-network-servers/find-a-lns-provider.mdx
> +[yosensi]: https://yosensi.io/management_platform/
Please keep this order the same.

2024-02-08 00:05 UTC, jthiller commented on docs/network-iot/run-an-lns/buy-an-oui.mdx
> +subject line 'Purchasing OUI' to the [Helium Foundation](mailto:hello@helium.foundation) containing
not necessary

2024-02-08 00:05 UTC, jthiller commented on docs/network-iot/run-an-lns/common-issues.mdx
> +Review the [Configuration Routing Rules](/iot/run-an-lns/configure-routing-rules) section.
```suggestion
Review the [Configuring Routing Rules](/iot/run-an-lns/configure-routing-rules) section.
```

2024-02-08 00:05 UTC, jthiller commented on docs/network-iot/run-an-lns/common-issues.mdx
> +As outlined in the [Fund an OUI](/iot/run-an-lns/fund-an-oui) section, if multibuy is not enabled,
this link should still say multibuy. the link can be improved by linking directly to the multibuy section.

2024-02-08 00:05 UTC, jthiller commented on docs/network-iot/run-an-lns/configure-chirpstack.mdx
> +[Routing Rules Configuration Guide](/iot/run-an-lns/configure-routing-rules).
the page is already inside the /iot/run-an-lns/ section so the prefix is not required.

2024-02-08 00:05 UTC, jthiller commented on docs/network-iot/run-an-lns/fund-an-oui.mdx
> +- [Fund an OUI using HNT](/iot/run-an-lns/fund-an-oui-using-hnt)
prefix not needed since this is in the /iot/run-an-lns section

2024-02-08 00:05 UTC, jthiller commented on docs/network-iot/run-an-lns/fund-an-oui.mdx
> +- [Fund an OUI using a credit card with the official Helium Data Credits Portal](/tokens/data-credit-portal)
prefer referring to the dc portal as Sphere's

2024-02-08 00:05 UTC, jthiller commented on docs/tokens/data-credit-portal.mdx
> +title: Helium Data Credits Portal
Tool is called the DC Portal, or "Data Credit Portal"

2024-02-08 00:05 UTC, jthiller commented on docs/tokens/data-credit-portal.mdx
> +title: Helium Data Credits Portal
apply to other instances.

2024-02-08 00:05 UTC, jthiller commented on docs/tokens/data-credit-portal.mdx
> +Access the official Helium Data Credits Portal at [dc-portal.helium.com][dc-portal].
revert

2024-02-08 00:05 UTC, jthiller commented on docs/tokens/data-credit-portal.mdx
> +If access appears to be restricted in your region, please [email][mailto-foundation] the Helium
show the email address

2024-02-08 17:35 UTC, Dumpling-girl commented on docs/network-iot/lorawan-network-servers/find-a-lns-provider.mdx
> +[yosensi]: https://yosensi.io/management_platform/
The links belowe were not in the same order as the companies in the list, I only re-ordered them alphabetically.

2024-02-08 19:50 UTC, Dumpling-girl commented
@jthiller I updated the docs after your feedback.

2024-02-13 03:47 UTC, jthiller requested changes
Please revert link changes in this PR. Broken links are breaking the build.

2024-02-14 16:24 UTC, Dumpling-girl commented
All checks failed. I edited all the pages that was up for review. I don't know what is wrong here.

2024-02-14 16:39 UTC, Dumpling-girl commented
All checks failed. I edited all the pages that was up for review. I don't know what is wrong here.

2025-01-02 17:18 UTC, closed without merging