Modified Governance page
helium/docs pull request #1769
Opened 2024-02-05 18:12 UTC by JustAnotherDevv

Changes:

- Changed [generic realms voting link](https://app.realms.today/realms) to [helius vote realms link](https://realms.heliumvote.com/realms)
- Fixed inconsistent use of `subDAOs` vs `subDAOS` to just `subDAOs`
- Added distinction between instructions for old vs new voting interface

2024-02-06 16:46 UTC, jthiller commented on docs/architecture/solana/migration/exchange.mdx
> +[Add Solana to Your Exchange](https://solana.com/docs/more/exchange) for details.
This change is already handled on main. Let's rebase this branch to pull in those changes.

2024-02-06 16:47 UTC, jthiller commented on sidebarsDocs.js
Let's keep syntax formatting out of PRs related to content changes.

2024-02-06 19:32 UTC, JustAnotherDevv commented on sidebarsDocs.js
Fixed

2024-02-07 16:40 UTC, waveform06 requested changes
the Compression nfts page is going to get updated so no need to delete, and no navigation to fix
We've moved away from Realms now to use a deployed instance of 
https://modular-governance.helium.com/
at https://heliumvote.com/
And prefer subnetworks to subDAOs

2024-02-08 03:11 UTC, JustAnotherDevv commented
> the Compression nfts page is going to get updated so no need to delete, and no navigation to fix We've moved away from Realms now to use a deployed instance of https://modular-governance.helium.com/ at https://heliumvote.com/ And prefer subnetworks to subDAOs

Will change subDAOs to subnetworks.

However I haven't seen https://modular-governance.helium.com/ mentioned anywhere in documentation before:
-  Is there a need to set up new pages for it with information and instructions how to use it? I can contribute to this if needed.
- If Realms are no longer used for governance should I remove pages related to them to help avoid confusion for new users?

2024-02-13 03:50 UTC, jthiller requested changes
Please rebase this PR to clean up the commit history for cleaner review.

2024-02-13 12:00 UTC, closed without merging