Updated docs from original PR #1757
helium/docs pull request #1777
Opened 2024-02-07 15:14 UTC by Dumpling-girl

Updated docs I put originally in PR #1757 and put the in a separate branch.

#Solana Scribes 2024.

2024-02-08 00:37 UTC, jthiller requested changes
Make sure the content of the pages is up to date before removing the legacy content banner.

2024-02-08 00:37 UTC, jthiller commented on docs/home/faq/helium-network.mdx
> +network in the world. [Watch this helpful introduction video](https://youtu.be/Vx9YyS7-d3g).
This section needs to be refactored post-migration (IoT and Mobile networks)

2024-02-08 00:37 UTC, jthiller commented on docs/home/faq/helium-network.mdx
> +[website](https://helium.foundation).
would linking to governance section be better?

2024-02-08 00:37 UTC, jthiller commented on docs/home/faq/helium-network.mdx
> +cellular service for regular devices such as computers and smartphones.
This section needs to be refactored for different hotspots

2024-02-08 19:28 UTC, Dumpling-girl commented on docs/home/faq/helium-network.mdx
> +[website](https://helium.foundation).
There is no clickable governance section on Fdn website. I will link to governance in the docs then.

2024-02-28 20:55 UTC, Dumpling-girl commented
Reworking this tomorrow morning.

2024-02-29 18:20 UTC, Dumpling-girl commented
Updated after the last feedback.

2025-01-02 17:18 UTC, closed without merging