Updated in governance section
helium/docs pull request #1809
Opened 2024-02-14 19:44 UTC by Dumpling-girl

Updated governance-faq.mdx
Updated governance.mdx
Updated voting.mdx
Updated links, wording subDAOs into subnetworks, staking into locking, changed references from Realms to Modular Governance/Helium Vote, etc.
Removing the legacy banners.

#Solana Scribes 2024

2024-02-17 21:05 UTC, jthiller requested changes
Quick skim presents a few areas for improvement. 
Please use consistent titlecase when rewriting titles and ensure the rewritten sentences are clear.

2024-02-17 21:05 UTC, jthiller commented on docs/governance/governance-faq.mdx
> +veHNT represents the Voting Power of the Helium Network.
I don't think voting power should be capitalized.

2024-02-17 21:05 UTC, jthiller commented on docs/governance/governance-faq.mdx
> +## What Are The Benefits of Locking HNT after The Subnetworks Launch?
subnetworks have launched. It is confusing to keep the pre-migration phrasing with the legacy content banner removed.

2024-02-17 21:05 UTC, jthiller commented on docs/governance/governance-faq.mdx
> +A lock-up period will incur when HNT is locked for veHNT. The lock-up period is between 1 day and 48
this needs to be rewritten

2024-02-17 21:05 UTC, jthiller commented on docs/governance/governance-faq.mdx
>  [HIP-51](https://github.com/helium/HIP/blob/main/0051-helium-dao.md#omni-protocol-poc-incentive-model)
Removed hyphen lower down, but not here.

2024-02-17 21:05 UTC, jthiller commented on docs/governance/governance-faq.mdx
> +## How to Lock Tokens By Using veHNT?
needs to be rewritten

2024-02-17 21:05 UTC, jthiller commented on docs/governance/governance-faq.mdx
> +## How Can veHNT be obtained?
this isn't proper titlecase

2024-02-28 18:48 UTC, Dumpling-girl commented on docs/governance/governance-faq.mdx
>  [HIP-51](https://github.com/helium/HIP/blob/main/0051-helium-dao.md#omni-protocol-poc-incentive-model)
Sorry, but I don't understand what you mean.

2025-01-02 17:17 UTC, closed without merging