Security Article for Makers
helium/docs pull request #182
Opened 2021-02-23 18:07 UTC by lthiery

2021-02-23 18:12 UTC, lthiery commented
I snuck in a bit of formatting and added them to `.git-blame-ignore-revs`, so please do not squash and merge.

2021-02-23 20:27 UTC, PharkMillups commented on docs/mine-hnt/hotspot-makers/security-requirements/security-requirements.mdx
> +# Security Requirements
```suggestion
## Security Requirements
```

2021-02-23 20:41 UTC, PharkMillups requested changes

2021-02-23 20:41 UTC, PharkMillups commented on docs/mine-hnt/hotspot-makers/security-requirements/security-requirements.mdx
> +# Securing the swarm_key with the ECC608
```suggestion
## Securing the swarm_key with the ECC608
```

2021-02-23 20:41 UTC, PharkMillups commented on docs/mine-hnt/hotspot-makers/security-requirements/security-requirements.mdx
> +sidebar_label: Docker Integration
```suggestion
sidebar_label: Security Requirements
```

2021-02-23 20:41 UTC, PharkMillups commented on docs/mine-hnt/hotspot-makers/security-requirements/security-requirements.mdx
> +is was made clear that open and easy access to the `swarm_key` is not permitted
```suggestion
it was made clear that open and easy access to the `swarm_key` is not permitted
```

2021-02-23 20:41 UTC, PharkMillups commented on docs/mine-hnt/hotspot-makers/security-requirements/security-requirements.mdx
> +is was made clear that open and easy access to the `swarm_key` is not permitted
Can we add some sort of "info" box about what the swarm key actually is?

2021-02-23 20:41 UTC, PharkMillups commented on docs/mine-hnt/hotspot-makers/security-requirements/security-requirements.mdx
> +And finally, you will want to extra the `onboarding_key` which is also called
```suggestion
And finally, you will want to extract the `onboarding_key` which is also called
```

2021-02-24 15:32 UTC, PharkMillups approved these changes

2021-02-24 15:32 UTC, merged