Update helium-network.mdx
helium/docs pull request #1839
Opened 2024-02-28 17:56 UTC by Kelechikizito

I add FAQs about the recent introduction of helium mobile
@jthiller please add the label and review, thanks.

2024-02-28 23:06 UTC, jthiller commented on docs/home/faq/helium-network.mdx
> +### How does Helium Mobile's plan utilize a mobile infrastructure and user hotspots?
```suggestion
### How does Helium Mobile's plan utilize a mobile infrastructure and user Hotspots?
```
We tend to always capitalize Hotspot as a proper noun

2024-02-28 23:06 UTC, jthiller commented on docs/home/faq/helium-network.mdx
> +Helium Mobile offers a competitively priced mobile phone plan in the United States, priced at $20 per month. This plan provides users with unlimited data, calls, and text, making it a cost-effective
Consider adding a link to hellohelium.com

2024-02-28 23:07 UTC, jthiller commented on docs/home/faq/helium-network.mdx
> +### How does Helium Mobile's plan utilize a mobile infrastructure and user hotspots?
Also instance of 'hotspots' below

2024-02-28 23:08 UTC, jthiller requested changes
Just some touchup for "Hotspots"

2024-03-01 07:40 UTC, Kelechikizito commented
> Just some touchup for "Hotspots"
I have touched up on Hotspot and added links to hellohelium.com

2025-01-02 17:17 UTC, closed without merging