Submission of updates regarding Helium documentation
helium/docs pull request #1858
Opened 2024-02-29 21:29 UTC by Bianca-Cassemiro

- Images have been added
- Texts have been improved
- Texts have been refactored for better reading

This was done on several mdx.

2024-02-29 21:55 UTC, jthiller requested changes
Please remove the committed package.json, .yarnrc.yml, and yarn.lock to clear things up for review.

2024-02-29 21:55 UTC, jthiller commented on docs/home/about-helium.mdx
> +The **Helium Network** represents an innovative approach to wireless infrastructure, operating in a decentralized <br/> manner and utilizing blockchain technology. This project enables both individua
All of these added `<br/>`s need to be removed (throughout this PR)

2024-03-07 23:40 UTC, jthiller commented
Thank you for submitting updates to the Helium Docs as part of the Solana Scribes Hackathon! Please follow the instructions in this form so we may begin issuing awards.

https://forms.gle/z4ovMHYDo7pzy8TN6  

Please complete this form by March 15, 2024. (Approximately 1 week from today). We had SO MANY great submissions and we’re eager to distribute the awards to all of the contributors.

2024-03-07 23:44 UTC, jthiller commented
Apologies, something happened to the Google forms link. This one should work: [https://forms.gle/z4ovMHYDo7pzy8TN6](https://forms.gle/z4ovMHYDo7pzy8TN6)

2024-03-08 22:53 UTC, Bianca-Cassemiro commented
Dattebayo

2025-01-02 17:17 UTC, closed without merging