Snapshot take and bake
helium/docs pull request #558
Opened 2021-08-05 16:55 UTC by jkowalcz

Add in Getting and loading the latest snapshots to your validator.  

**I'm unsure of the syntax of a info block as preview does not accurately show them please review closely**

2021-08-05 19:27 UTC, abhay commented on docs/mine-hnt/validators/troubleshooting.mdx
> +* Resume transaction syncing via ```miner repair sync_resume```
nit: This shouldn't be necessary.

2021-08-05 19:28 UTC, abhay commented on docs/mine-hnt/validators/troubleshooting.mdx
> +* On a running Validator run `miner snapshot list`
I would also add a step to verify in the API on the heights available:

https://api.helium.io/v1/snapshots

2021-08-05 19:28 UTC, abhay commented on docs/mine-hnt/validators/troubleshooting.mdx
> +For the time/blocks when your validator accrued penalties, check your metrics dashboard (e.g., Grafana) [Baselining Your Validator](https://docs.helium.com/mine-hnt/validators/requirements).
stray commit?

2021-08-05 19:29 UTC, abhay requested changes
Nice. Thanks for putting this in the docs.

2021-08-06 10:15 UTC, kellybyrd commented on docs/mine-hnt/validators/troubleshooting.mdx
> +* Move the `/var/data/snap-<height>` file into your root of the `validator_data` directory on the destination Validator
For docker builds, `/var/data/...` is inside the container, it will be `validator_data` on the host of the source validator.

2021-08-06 10:17 UTC, kellybyrd commented on docs/mine-hnt/validators/troubleshooting.mdx
> +* Load snapshot from downloaded file ```miner snapshot load /var/data/snap-<height>```
nit: This load cmd may "timeout" and look like it fails, but the load continues in the background. Same note applies to load from a trusted validator. Not sure if you need to mention this or not.

2021-08-10 19:35 UTC, abhay submitted a review, later dismissed
one small addition but LGTM

2021-08-10 19:35 UTC, abhay commented on docs/mine-hnt/validators/troubleshooting.mdx
> +* Find the highest "Height" block and download the snapshot from Helium via `curl -O https://snapshots.helium.wtf/mainnet/snap-<height>`.
```suggestion
* Find the highest "Height" block and download the snapshot from Helium via `curl -O https://snapshots.helium.wtf/mainnet/snap-<height>`. If this snapshot is not available, try the next highest as the consensus group may have not agreed upon the snapshot.
```

2021-08-10 20:22 UTC, kellybyrd commented
LGTM

2021-08-13 14:59 UTC, jkowalcz commented on docs/mine-hnt/validators/troubleshooting.mdx
> +* On a running Validator run `miner snapshot list`
OK good to know I didn't know that API endpoint.

2021-08-13 14:59 UTC, jkowalcz commented on docs/mine-hnt/validators/troubleshooting.mdx
> +* On a running Validator run `miner snapshot list`
I added the API endpoint in the docs.

2021-08-13 14:59 UTC, jkowalcz commented on docs/mine-hnt/validators/troubleshooting.mdx
> +* Resume transaction syncing via ```miner repair sync_resume```
So I've has a few times where it's needed so I added in a line to check if it's active again, if not I documented how to resume it just in case.

2021-08-13 14:59 UTC, jkowalcz commented on docs/mine-hnt/validators/troubleshooting.mdx
> +* Move the `/var/data/snap-<height>` file into your root of the `validator_data` directory on the destination Validator
So I added in "For this example `/var/data` is inside the docker container which is mapped to your `validator_data` directory on the host system" in the note section to make sure that is clear.

2021-08-13 14:59 UTC, jkowalcz commented on docs/mine-hnt/validators/troubleshooting.mdx
> +For the time/blocks when your validator accrued penalties, check your metrics dashboard (e.g., Grafana) [Baselining Your Validator](https://docs.helium.com/mine-hnt/validators/requirements).
yes it was not clear, I added a sentence to the bottom of the section to point people to a "easier" way to look at your baseline performance.

2021-08-13 14:59 UTC, jkowalcz commented on docs/mine-hnt/validators/troubleshooting.mdx
> +* Load snapshot from downloaded file ```miner snapshot load /var/data/snap-<height>```
Added in " This command may look like it fails with a timeout error.  The load actually continues in the background and you will need to wait and review the blockchain height in a few minutes."

2021-08-17 01:56 UTC, PharkMillups approved these changes
Merging!

2021-08-17 01:56 UTC, merged