Console: Add info on backing up the swarm key
helium/docs pull request #562
Opened 2021-08-06 14:02 UTC by mfalkvidd

Backing up the swarm key is an important part of maintaining a router.

2021-08-07 16:57 UTC, abhay commented on docs/use-the-network/run-a-network-server/run-console/run-console.mdx
> +The `swarm_key` equates to your validator's unique identity on the Helium blockchain. Backing up the `swarm_key` enables you to maintain your validator's identity in the event that your node becomes
```suggestion
The `swarm_key` equates to your validator's unique identity on the Helium blockchain. Backing up the `swarm_key` enables you to maintain your router's identity in the event that your node becomes compromised in some way, or needs to be rebuilt on another server for any reason.
```

2021-08-07 16:57 UTC, abhay requested changes
Small edit

2022-02-16 21:13 UTC, PharkMillups approved these changes
I think this is still accurate. Going to merge. If not, someone please complain loudly.

2022-02-16 21:14 UTC, PharkMillups commented
@abhay Is this good to go?

2022-02-16 21:43 UTC, abhay approved these changes

2022-02-16 21:54 UTC, merged