Phark/blockchain additions
helium/docs pull request #58
Opened 2020-12-22 17:26 UTC by PharkMillups

2020-12-22 19:32 UTC, lthiery requested changes
just some dangling bullets but perhaps you were going to finish this before landing?

2020-12-22 19:32 UTC, lthiery commented on docs/blockchain/helium-token/helium-token.mdx
> +*
```suggestion

```

2020-12-22 19:32 UTC, lthiery commented on docs/blockchain/helium-token/helium-token.mdx
> +*
```suggestion

```

2020-12-23 18:42 UTC, kent-williams approved these changes
LGTM

2020-12-23 19:03 UTC, kent-williams approved these changes

2020-12-23 19:05 UTC, lthiery approved these changes

2020-12-23 19:10 UTC, merged