docs for config profiles
helium/docs pull request #656
Opened 2021-10-15 22:55 UTC by jdgemm

staging docs for config profiles

2021-10-15 23:24 UTC, kent-williams commented on docs/use-the-network/console/profiles.mdx
> +[CURRENTLY ON STAGING ONLY]
Did you mean to display brackets here?

2021-10-18 23:12 UTC, jdgemm commented on docs/use-the-network/console/profiles.mdx
> +[CURRENTLY ON STAGING ONLY]
yes

2021-10-19 16:51 UTC, PharkMillups commented on docs/use-the-network/console/alerts.mdx
> +Alerts (email or webhooks) can be configured for a number of conditions related to devices and integrations including when devices are deleted, integrations updated or deleted.
```suggestion
Alerts (email or webhooks) can be configured for a number of conditions related to devices and integrations including when devices are deleted, or when integrations are updated or deleted.
```

2021-10-19 16:52 UTC, PharkMillups commented on docs/use-the-network/console/alerts.mdx
> +For a video walkthrough of how to set up Alerts in Console 2.0, check out our Tips & Tricks video [here](https://youtu.be/8zt6W_FCQcM)
```suggestion
For a video walkthrough of how to set up Alerts in Console 2.0, check out our Tips & Tricks video [here](https://youtu.be/8zt6W_FCQcM).
```

2021-10-19 16:52 UTC, PharkMillups commented on docs/use-the-network/console/alerts.mdx
> +To configure alerts from the Flows workspace, select a Device/Label node or Integration node depending on the type of alert to configure and select the Inspector tab.
```suggestion
To configure alerts from the Flows workspace, select a Device/Label node or Integration node depending on the type of alert you want to configure and select the Inspector tab. 
```

2021-10-19 16:53 UTC, PharkMillups commented on docs/use-the-network/console/alerts.mdx
> +**Note:** for webhook alerts obtain a webhook key for authorization, by choosing Organizations from the side menu and copying relevant webhook key.
```suggestion
**Note:** For webhook alerts, obtain a webhook key for authorization by choosing Organizations from the side menu and copying relevant webhook key.
```

2021-10-19 16:53 UTC, PharkMillups commented on docs/use-the-network/console/multi-packets.mdx
> +Data Credits are only charged for uplinks. The Multiple Packets feature provides the ability to pay for additional packets for redundancy and location triangulation purposes.
```suggestion
By default, Data Credits are only charged for uplinks. The Multiple Packets feature provides the ability to pay for additional packets for redundancy and location triangulation purposes. 
```

2021-10-19 16:54 UTC, PharkMillups commented on docs/use-the-network/console/multi-packets.mdx
> +**Note:** Regardless of the Multiple Packet feature setting, under certain conditions the system purchases multiple packets to help ensure successful packet transmission (these cost additional Data C
```suggestion
**Note:** Regardless of the Multiple Packet feature setting, under certain conditions the system purchases multiple packets to help ensure successful packet transmission (these cost additional Data Credits and happen automatically). These include: initial joining of the device (up to five packets) and downlinks that contain data payloads (up to three packets). These additional packets help ensure connection reliability to downlink via the Hotspot with the strongest connection.
```

2021-10-19 16:55 UTC, PharkMillups commented on docs/use-the-network/console/profiles.mdx
> +Configuration Profiles can be added to device/label nodes. The last Profile assigned to a device takes priority.  For example, if a device has Profile A, and a label has Profile B, if that label is a
```suggestion
Configuration Profiles can be added to Device/Label nodes. The last Profile assigned to a device takes priority.  For example, if a device has Profile A, and a label has Profile B, if that label is applied to the device then Profile B overrides Profile A. 
```

2021-10-19 16:55 UTC, PharkMillups commented on docs/use-the-network/console/profiles.mdx
> +Adaptive Data Rate or ADR is a mechanism for adapting the data rate of devices
```suggestion
Adaptive Data Rate (ADR) is a mechanism for adapting the data rate of devices
```

2021-10-19 17:08 UTC, PharkMillups requested changes
Made some small suggestions.

2021-10-20 19:51 UTC, PharkMillups approved these changes
Gucci

2021-10-20 19:51 UTC, merged