update timeline
helium/docs pull request #695
Opened 2021-11-30 00:20 UTC by cokes518

2021-11-30 13:59 UTC, abhay requested changes

2021-11-30 13:59 UTC, abhay commented on docs/wallets/ledger.mdx
> +Ledger CLI using experimental mode is supported at this time. Work to enable HNT in Ledger Live without a CLI is ongoing.
I'd say "in addition" to the CLI since some folks like that too.

2021-12-08 23:30 UTC, kent-williams approved these changes

2021-12-13 01:50 UTC, abhay approved these changes

2021-12-13 01:50 UTC, merged