Adds documentation outlining vote configuration
helium/docs pull request #706
Opened 2021-12-08 22:33 UTC by jthiller

Takes a first pass at documenting [Helium Vote](https://helium.vote) and some details around the configuration of a vote.

For visibility cc/ @abhay @cokes518

2021-12-08 23:10 UTC, cokes518 commented
nice guide @jthiller. One thing I noticed is that "Voting Power" is specially based off HIP39 voting and may not apply to future votes. This "Voting Power" may not be token-based in future votes, depending on the issue at hand. For example, a vote on AU915 may be number of Hotspots owned by a voting wallet that is asserted in Australia. 

I'd recommend detailing that Voting Power may change vote-to-vote, depending on what the community is reaching consensus on.

2021-12-08 23:11 UTC, jthiller commented
fantastic! Thanks I'll get that noted.

-Joey Hiller
707.456.7374

On Wed, Dec 08, 2021 at 3:10 PM, Coco Tang < ***@***.*** > wrote:

> 
> 
> 
> nice guide @ jthiller ( https://github.com/jthiller ). One thing I noticed
> is that "Voting Power" is specially based off HIP39 voting and may not
> apply to future votes. This "Voting Power" may not be token-based in
> future votes, depending on the issue at hand. For example, a vote on AU915
> may be number of Hotspots owned by a voting wallet that is asserted in
> Australia.
> 
> 
> 
> I'd recommend detailing that Voting Power may change vote-to-vote,
> depending on what the community is reaching consensus on.
> 
> 
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub (
> https://github.com/helium/docs/pull/706#issuecomment-989301138 ) , or unsubscribe
> (
> https://github.com/notifications/unsubscribe-auth/AAO7X7NHNW6GDJTKR6ZMZZLUP7QVJANCNFSM5JU53BSA
> ).
> 
> 
>

2021-12-20 18:57 UTC, jthiller commented
This is ready for review/merge.

2022-01-22 22:10 UTC, lthiery requested changes
I prefer a more general statement around the hotspot voting.

2022-01-22 22:10 UTC, lthiery commented on docs/community-governance/community-voting.mdx
> +For most votes, voting power is currently determined by the HNT balance of the voting wallets at a rate of one vote per HNT. However, voting power may change vote-to-vote, depending on what the commu
```suggestion
For most votes, voting power is currently determined by the HNT balance of the voting wallets at a rate of one vote per HNT. However, voting power may change vote-to-vote, depending on what the community is reaching consensus on. As example, a vote on on frequency plan for a region would only concern Hotspots in the region and one would use number Hotspots in the region as votes. Proposals to implement more involved voting mechanisms have been presented, but have not been voted on or implemented yet. See: [HIP41](https://github.com/helium/HIP/blob/master/0041-governance-by-token-lock-v2.md)
```

2022-01-24 20:55 UTC, lthiery approved these changes

2022-01-24 20:55 UTC, merged