Add Blockdaemon as a provider.
helium/docs pull request #723
Opened 2022-01-10 17:50 UTC by jer117

Add Blockdaemon as a provider to docs to be displayed on this page. 

https://docs.helium.com/mine-hnt/validators/faqs-resources-providers/#staking-providers

2022-01-11 14:58 UTC, kellybyrd requested changes
The rest of the list is alphabetized, your new entry should be too.

2022-01-22 22:00 UTC, lthiery commented
@jer117 as mentioned, please maintain the alphabetical order

2022-01-24 14:28 UTC, jer117 commented
@lthiery done.

2022-01-24 20:54 UTC, lthiery approved these changes

2022-01-24 20:54 UTC, merged